import { actionOffset, durations, Random, Spring, targets } from "./targets.ts";
import { blend, renderFace } from "./face.ts";
import {
  clamp,
  item,
  type Behavior,
  type Expression,
  type Frame,
  type OrbModel,
  type Pointer,
  type Vec3,
} from "./types.ts";

/** Fixed-step numerical port. Profile data and parity frames are generated by Swift. */
export class OrbMotion {
  model: OrbModel;
  program: string;
  behavior: Behavior;
  pointer: Pointer | null = null;
  time = 0;
  private random: Random;
  private ticks = 0;
  private remainder = 0;
  private programAt = 0;
  private enteredAt = 0;
  private blinkAt = -10;
  private doubleBlink = false;
  private nextBlink = 0;
  private nextExpression = 0;
  private nextGlance = 0;
  private nextAction = 0;
  private expressionIndex = 0;
  private glance = { x: 0, y: 0 };
  private action = "";
  private actionAt = 0;
  private expression: Expression;
  private previousExpression: Expression;
  private expressionAt = -10;
  private hasEnteredHero: boolean;
  private channels = {
    yaw: new Spring(),
    pitch: new Spring(),
    roll: new Spring(),
    y: new Spring(),
    squash: new Spring(1),
    lid: new Spring(1),
    x: new Spring(),
    py: new Spring(),
  };

  constructor(model: OrbModel, program = "hero", seed = 1) {
    this.model = model;
    this.program = program;
    this.hasEnteredHero = program === "hero";
    this.behavior = this.profile(this.cue(0));
    this.expression = this.face(item(this.behavior.expressions, 0));
    this.previousExpression = this.expression;
    this.random = new Random(seed);
    this.scheduleEntry();
  }

  private profile(id: string): Behavior {
    const p = this.model.behaviors.find((p) => p.id === id);
    if (!p) throw new Error(`Unknown Orb behavior ${id}`);
    return p;
  }
  private face(id: string): Expression {
    const e = this.model.expressions.find((e) => e.id === id);
    if (!e) throw new Error(`Unknown Orb expression ${id}`);
    return e;
  }

  cue(time: number): string {
    const p = this.model.programs[this.program];
    if (!p) return this.program;
    const intro = p.cues
      .slice(0, p.loopFrom)
      .reduce((a, c) => a + c.duration, 0);
    const loop = p.cues.slice(p.loopFrom).reduce((a, c) => a + c.duration, 0);
    let t = Math.max(0, Number.isFinite(time) ? time : 0);
    if (t >= intro) t = intro + ((t - intro) % loop);
    for (const cue of p.cues) {
      if (t < cue.duration - 1e-9) return cue.state;
      t -= cue.duration;
    }
    return item(p.cues, p.loopFrom).state;
  }

  setProgram(program: string): void {
    if (program === this.program) return;
    this.program = program;
    const elapsed = program === "hero" && this.hasEnteredHero ? 2.2 : 0;
    if (program === "hero") this.hasEnteredHero = true;
    this.programAt = this.time - elapsed;
    this.enter(this.cue(elapsed));
  }

  advance(delta: number): Frame {
    if (Number.isFinite(delta) && delta > 0) {
      this.remainder += Math.min(delta, 0.064);
      while (this.remainder + 1e-12 >= 1 / 120) {
        this.remainder -= 1 / 120;
        this.tick();
      }
    }
    return this.frame();
  }

  private tick(): void {
    this.time = ++this.ticks * (1 / 120);
    const state = this.cue(this.time - this.programAt);
    if (state !== this.behavior.id) this.enter(state);
    this.events();
    const t = targets(this.behavior.style, this.time - this.enteredAt);
    const weight = this.pointer === null ? 1 : 0.2;
    const c = this.channels;
    c.yaw.step(t.yaw + this.glance.x * weight, 5);
    c.pitch.step(t.pitch + this.glance.y * weight, 5);
    c.roll.step(t.roll, 5);
    c.y.step(t.y, 10);
    c.squash.step(t.squash, 10);
    c.lid.step(Math.min(t.lid, this.blinkTarget()), 26);
    const finite = (v: number): number =>
      Number.isFinite(v) ? clamp(v, -1, 1) : 0;
    c.x.step(finite(this.pointer?.x ?? 0) * 8);
    c.py.step(finite(this.pointer?.y ?? 0) * -5);
  }

  private setExpression(id: string): void {
    if (id === this.expression.id) return;
    this.previousExpression = this.currentExpression();
    this.expression = this.face(id);
    this.expressionAt = this.time;
  }

  private enter(id: string): void {
    this.behavior = this.profile(id);
    this.enteredAt = this.time;
    this.expressionIndex = 0;
    this.setExpression(item(this.behavior.expressions, 0));
    this.glance = { x: 0, y: 0 };
    if (!["sleeping", "waking", "drowsy"].includes(id)) {
      this.blinkAt = this.time;
      this.doubleBlink = false;
    }
    this.scheduleEntry();
  }

  private scheduleEntry(): void {
    this.nextBlink = this.time + this.random.interval([1.5, 7]);
    this.nextExpression =
      this.time + this.random.interval(this.behavior.expression);
    this.nextGlance = this.time + this.random.interval(this.behavior.glance);
    this.nextAction = this.time + this.random.interval([2.5, 5]);
  }

  private events(): void {
    const p = this.behavior;
    if (this.time >= this.nextBlink) {
      this.blinkAt = this.time;
      this.doubleBlink = this.random.next() < 0.14;
      this.nextBlink = this.time + this.random.interval(p.blink);
    }
    if (this.time >= this.nextExpression) {
      if (p.expressions.length > 1) {
        const skip =
          1 + Math.floor(this.random.next() * (p.expressions.length - 1));
        this.expressionIndex =
          (this.expressionIndex + skip) % p.expressions.length;
        this.setExpression(item(p.expressions, this.expressionIndex));
      }
      this.nextExpression = this.time + this.random.interval(p.expression);
    }
    if (this.time >= this.nextGlance) {
      const spread = ["rest", "sleep"].includes(p.style) ? 0 : 10.5;
      this.glance = {
        x: (this.random.next() * 2 - 1) * spread,
        y: (this.random.next() * 2 - 1) * spread * 0.6,
      };
      this.nextGlance = this.time + this.random.interval(p.glance);
    }
    if (this.time >= this.nextAction) this.chooseAction();
  }

  private chooseAction(): void {
    const p = this.behavior;
    if (
      p.actions.length &&
      this.time - this.actionAt >= (durations[this.action] ?? 0)
    ) {
      const r = this.random.next();
      const i =
        p.id === "playful"
          ? r < 0.34
            ? 0
            : r < 0.62
              ? 1
              : r < 0.86
                ? 2
                : 3
          : r < 0.55
            ? 0
            : 1;
      this.action = item(p.actions, Math.min(i, p.actions.length - 1));
      this.actionAt = this.time;
    }
    this.nextAction =
      this.time + (p.id === "celebrate" ? 6.2 : this.random.interval([9, 18]));
  }

  private blinkTarget(): number {
    const t = this.time - this.blinkAt;
    if (t < 0.15) return 0.05;
    if (t < 0.3) return 1.08;
    if (this.doubleBlink && t >= 0.37 && t < 0.48) return 0.05;
    return 1;
  }

  get pointerOffset(): Pointer {
    return { x: this.channels.x.value, y: this.channels.py.value };
  }

  frame(): Frame {
    const e = this.currentExpression();
    const c = this.channels,
      a = actionOffset(this.action, this.time - this.actionAt);
    const gaze: Vec3 = [
      e.gaze[0] + c.yaw.value + c.x.value + a.yaw,
      e.gaze[1] + c.pitch.value + c.py.value,
      e.gaze[2] + c.roll.value + a.roll,
    ];
    return renderFace(e, gaze, c.y.value + a.y, c.squash.value, c.lid.value);
  }

  private currentExpression(): Expression {
    const t = clamp((this.time - this.expressionAt) / 0.45);
    return blend(
      this.previousExpression,
      this.expression,
      1 - Math.pow(1 - t, 5)
    );
  }
}
