import {
  actionDuration,
  actionOffset,
  blendShiver,
  dizzyTurns,
  noOffset,
  type Offset,
} from "./actions.ts";
import {
  accents,
  actionCeilings,
  eyeScales,
  glanceSpread,
  impulses,
  lidFloors,
  shivers,
} from "./behaviors.ts";
import {
  ConfettiField,
  RibbonField,
  pokeBurstCount,
  wakeBurstCount,
} from "./decor.ts";
import { Random, Spring, targets } from "./targets.ts";
import { blend, renderFace } from "./face.ts";
import {
  clamp,
  item,
  type Behavior,
  type Expression,
  type Frame,
  type OrbModel,
  type Pointer,
  type Vec3,
} from "./types.ts";

/** 两记大动作之间至少隔这么久，秒。 */
const actionGap = 4;
/** 戳一下按序轮转的五记反应。 */
const pokeOrder = [
  "spin",
  "spinTwice",
  "spinBounce",
  "spinDizzy",
  "spinConfetti",
];

/** Fixed-step numerical port. Profile data and parity frames are generated by Swift. */
export class OrbMotion {
  model: OrbModel;
  program: string;
  behavior: Behavior;
  pointer: Pointer | null = null;
  time = 0;
  private random: Random;
  private ticks = 0;
  private remainder = 0;
  private programAt = 0;
  private enteredAt = 0;
  private blinkAt = -10;
  private doubleBlink = false;
  private nextBlink = 0;
  private nextExpression = 0;
  private nextGlance = 0;
  private nextAction = 0;
  /** 下一记重音的落点，以及这一记演到哪一刻。 */
  private nextAccent = Infinity;
  private accentUntil = 0;
  private expressionIndex = 0;
  private glance = { x: 0, y: 0 };
  private action = "";
  private actionAt = 0;
  /** 这一记晕眩转抽到的圈数，整数。别的几记不读它。 */
  private actionTurns = 4;
  private ribbons = new RibbonField();
  private confetti = new ConfettiField();
  /** 戳球五记反应的序号。 */
  private pokes = 0;
  /** 唤醒入场撒花的落点，null 即这一幕不撒。 */
  private wakeBurstAt: number | null = null;
  private expression: Expression;
  private previousExpression: Expression;
  private expressionAt = -10;
  /** 已经演过登场段的那几幕。 */
  private entered: Set<string>;
  /**
   * 静息头部朝向，也就是 OrbPose.rest 的那一份。
   * 会自己换脸的这台引擎不让头跟着表情转：换 25 张眼形都不动头。
   */
  private restGaze: Vec3;
  private channels = {
    yaw: new Spring(),
    pitch: new Spring(),
    roll: new Spring(),
    lift: new Spring(),
    /** 横向位移。官网 `u` 那一条，ω 3.5。 */
    sway: new Spring(),
    squash: new Spring(1),
    lid: new Spring(1),
    /** 眼睛缩放。官网 `M` 那一条，ω 9、ζ 0.85。 */
    eyeScale: new Spring(1),
    pointerX: new Spring(),
    pointerY: new Spring(),
  };

  constructor(model: OrbModel, program = "hero", seed = 1) {
    this.model = model;
    this.program = program;
    this.entered = new Set([program]);
    this.behavior = this.profile(this.cue(0));
    this.random = new Random(seed);
    this.restGaze = this.face("neutral").gaze;
    this.expression = this.face(item(this.behavior.expressions, 0));
    this.previousExpression = this.expression;
    this.scheduleEntry();
    // 大动作那条计时器只在这里设一次，之后跨状态连续走。
    this.nextAction = this.time + this.random.interval([2.5, 5]);
  }

  private profile(id: string): Behavior {
    const p = this.model.behaviors.find((p) => p.id === id);
    if (!p) throw new Error(`Unknown Orb behavior ${id}`);
    return p;
  }
  private face(id: string): Expression {
    const e = this.model.expressions.find((e) => e.id === id);
    if (!e) throw new Error(`Unknown Orb expression ${id}`);
    return e;
  }

  /** 登场段有多长，秒。回到这一幕不重演登场。 */
  private introLength(program: string): number {
    const p = this.model.programs[program];
    if (!p) return 0;
    return p.cues.slice(0, p.loopFrom).reduce((a, c) => a + c.duration, 0);
  }

  cue(time: number): string {
    const p = this.model.programs[this.program];
    if (!p) return this.program;
    const intro = this.introLength(this.program);
    const loop = p.cues.slice(p.loopFrom).reduce((a, c) => a + c.duration, 0);
    let t = Math.max(0, Number.isFinite(time) ? time : 0);
    if (t >= intro) t = intro + ((t - intro) % loop);
    for (const cue of p.cues) {
      if (t < cue.duration - 1e-9) return cue.state;
      t -= cue.duration;
    }
    return item(p.cues, p.loopFrom).state;
  }

  /** 业务换场不重建引擎，也不丢弃当前弹簧速度。 */
  setProgram(program: string): void {
    if (program === this.program) return;
    this.program = program;
    const elapsed = this.entered.has(program) ? this.introLength(program) : 0;
    this.entered.add(program);
    this.programAt = this.time - elapsed;
    this.enter(this.cue(elapsed));
  }

  advance(delta: number): Frame {
    if (Number.isFinite(delta) && delta > 0) {
      this.remainder += Math.min(delta, 0.064);
      while (this.remainder + 1e-12 >= 1 / 120) {
        this.remainder -= 1 / 120;
        this.tick();
      }
    }
    return this.frame();
  }

  private tick(): void {
    this.time = ++this.ticks * (1 / 120);
    const state = this.cue(this.time - this.programAt);
    if (state !== this.behavior.id) this.enter(state);
    this.events();
    const t = targets(this.behavior.style, this.time - this.enteredAt);
    const weight = this.pointer === null ? 1 : 0.2;
    t.yaw += this.glance.x * weight;
    t.pitch += this.glance.y * weight;
    t.lid = Math.min(
      t.lid,
      this.blinkTarget(),
      lidFloors[this.behavior.id] ?? 1
    );
    t.eyeScale = eyeScales[this.behavior.id] ?? 1;
    this.accentuate(t);
    const c = this.channels;
    c.yaw.step(t.yaw, 5);
    c.pitch.step(t.pitch, 5);
    c.roll.step(t.roll, 5);
    c.lift.step(t.y, 10);
    c.sway.step(t.x, 3.5);
    c.squash.step(t.squash, 10);
    c.lid.step(t.lid, 26);
    c.eyeScale.step(t.eyeScale, 9, 0.85);
    const finite = (v: number): number =>
      Number.isFinite(v) ? clamp(v, -1, 1) : 0;
    c.pointerX.step(finite(this.pointer?.x ?? 0) * 8);
    c.pointerY.step(finite(this.pointer?.y ?? 0) * -5);
    this.ribbons.step(this.offset().spin, this.time, 1 / 120, this.random);
    this.confetti.sweep(this.time);
  }

  /** 这一刻那记重音叠给横向位移与侧倾的份额。形状是半正弦。 */
  private accentuate(target: { x: number; roll: number }): void {
    const accent = accents[this.behavior.id];
    if (!accent || this.time >= this.accentUntil) return;
    const share = Math.sin(
      Math.PI * (1 - (this.accentUntil - this.time) / accent.duration)
    );
    target.x += accent.sway * share;
    target.roll += accent.roll * share;
  }

  private setExpression(id: string): void {
    if (id === this.expression.id) return;
    this.previousExpression = this.currentExpression();
    this.expression = this.face(id);
    this.expressionAt = this.time;
  }

  private enter(id: string): void {
    this.behavior = this.profile(id);
    this.enteredAt = this.time;
    this.expressionIndex = 0;
    this.setExpression(item(this.behavior.expressions, 0));
    this.glance = { x: 0, y: 0 };
    if (!["sleeping", "waking", "drowsy"].includes(id)) {
      this.blinkAt = this.time;
      this.doubleBlink = false;
    }
    this.scheduleEntry();
    // 速度冲量在入场那一帧踢一脚。
    const impulse = impulses[id];
    if (impulse) {
      this.channels.roll.kick(impulse.roll);
      this.channels.lift.kick(impulse.lift);
    }
  }

  private scheduleEntry(): void {
    const p = this.behavior;
    this.nextBlink = this.time + this.random.interval([1.5, 7]);
    this.nextExpression = this.time + this.random.interval(p.expression);
    this.nextGlance = this.time + this.random.interval(p.glance);
    const accent = accents[p.id];
    this.nextAccent = accent
      ? this.time + this.random.interval(accent.interval)
      : Infinity;
    this.accentUntil = 0;
    // 唤醒那一幕入场 0.2 秒撒一把花。
    this.wakeBurstAt = p.id === "waking" ? this.time + 0.2 : null;
  }

  private events(): void {
    const p = this.behavior;
    if (this.time >= this.nextBlink) {
      this.blinkAt = this.time;
      this.doubleBlink = this.random.next() < 0.14;
      this.nextBlink = this.time + this.random.interval(p.blink);
    }
    if (this.time >= this.nextExpression) this.changeExpression();
    if (this.time >= this.nextGlance) {
      // 幅度逐状态：闲着的时候是 0，好奇横 ±9 到 ±15。
      const spread = glanceSpread(p.id);
      this.glance = {
        x: this.random.sign() * this.random.interval(spread.yaw),
        y: (this.random.next() * 2 - 1) * spread.pitch,
      };
      this.nextGlance =
        this.time + this.random.interval(spread.retarget ?? p.glance);
    }
    const accent = accents[p.id];
    if (accent && this.time >= this.nextAccent) {
      this.accentUntil = this.time + accent.duration;
      this.nextAccent = this.time + this.random.interval(accent.interval);
    }
    if (this.time >= this.nextAction) this.chooseAction();
    if (this.wakeBurstAt !== null && this.time >= this.wakeBurstAt) {
      this.wakeBurstAt = null;
      this.confetti.burst(
        Math.round(this.random.interval(wakeBurstCount)),
        this.time,
        this.random
      );
    }
  }

  private changeExpression(): void {
    const p = this.behavior;
    if (p.expressions.length > 1) {
      const skip =
        1 + Math.floor(this.random.next() * (p.expressions.length - 1));
      this.expressionIndex =
        (this.expressionIndex + skip) % p.expressions.length;
      this.setExpression(item(p.expressions, this.expressionIndex));
    }
    this.nextExpression = this.time + this.random.interval(p.expression);
  }

  /** 这一幕抽得到哪几记动作。幕的上限把长的挡在外面，抽签的分布照旧。 */
  private eligibleActions(): string[] {
    const ceiling = actionCeilings[this.program] ?? Infinity;
    return this.behavior.actions.filter((a) => actionDuration(a) <= ceiling);
  }

  /**
   * 计时器是一条固定周期的节拍器：9 到 18 秒一拍，跨状态连续走，不随入场重置。
   * 到点那一刻若这一幕抽不出动作就一直等着，等掉的时间不白等：续期从上一次到点算起。
   */
  private chooseAction(): void {
    const eligible = this.eligibleActions();
    if (!eligible.length) return;
    const beat =
      this.behavior.id === "celebrate" ? 6.2 : this.random.interval([9, 18]);
    if (this.isActing) {
      this.nextAction = this.time + beat;
      return;
    }
    const pick = this.random.next();
    const index =
      this.behavior.id === "playful"
        ? pick < 0.34
          ? 0
          : pick < 0.62
            ? 1
            : pick < 0.86
              ? 2
              : 3
        : pick < 0.55
          ? 0
          : 1;
    this.start(item(eligible, Math.min(index, eligible.length - 1)));
    this.nextAction = Math.max(this.nextAction + beat, this.time + actionGap);
  }

  /** 手动发一记。播放中忽略。 */
  act(kind: string): void {
    if (!this.isActing) this.start(kind);
  }

  /**
   * 戳了道长一下：五记反应按序轮转。
   * 大动作在播、或者飘带还没散尽，这一下就不受理，不打断也不排队。
   */
  poke(): void {
    if (this.isActing) return;
    const pick = item(pokeOrder, this.pokes);
    this.pokes = (this.pokes + 1) % pokeOrder.length;
    this.start(pick);
  }

  /** 此刻有没有一记大动作在演，飘带还没散尽也算。 */
  get isActing(): boolean {
    if (
      this.action &&
      this.time - this.actionAt < actionDuration(this.action, this.actionTurns)
    )
      return true;
    return this.ribbons.busy;
  }

  private start(kind: string): void {
    this.actionTurns = Math.round(this.random.interval(dizzyTurns));
    this.action = kind;
    this.actionAt = this.time;
    if (kind === "spinConfetti")
      this.confetti.burst(pokeBurstCount, this.time, this.random);
  }

  /** 这一刻叠在弹簧输出之后的那一份偏差：抽中的那记动作，加上这一幕自带的颤跳。 */
  private offset(): Offset {
    const out = this.action
      ? actionOffset(this.action, this.time - this.actionAt, this.actionTurns)
      : noOffset();
    const shiver = shivers[this.program];
    if (shiver) blendShiver(out, shiver, this.time - this.programAt);
    return out;
  }

  private blinkTarget(): number {
    const t = this.time - this.blinkAt;
    if (t < 0.15) return 0.05;
    if (t < 0.3) return 1.08;
    if (this.doubleBlink && t >= 0.37 && t < 0.48) return 0.05;
    return 1;
  }

  get pointerOffset(): Pointer {
    return { x: this.channels.pointerX.value, y: this.channels.pointerY.value };
  }

  frame(): Frame {
    const e = this.currentExpression();
    const c = this.channels,
      a = this.offset();
    const gaze: Vec3 = [
      this.restGaze[0] + c.yaw.value + c.pointerX.value + a.yaw,
      this.restGaze[1] + c.pitch.value + c.pointerY.value,
      this.restGaze[2] + c.roll.value + a.roll,
    ];
    return renderFace(
      e,
      gaze,
      { x: c.sway.value, y: c.lift.value + a.y },
      c.squash.value,
      Math.min(c.lid.value, a.lid),
      c.eyeScale.value
    );
  }

  private currentExpression(): Expression {
    const t = clamp((this.time - this.expressionAt) / 0.45);
    return blend(
      this.previousExpression,
      this.expression,
      1 - Math.pow(1 - t, 5)
    );
  }
}
